os: linux
distro: bionic
language: node_js
notifications:
    email: false
node_js:
    - 12
    - 11
    - 10
install: yarn install
jobs:
    include:
        # - stage: build
        #   script: yarn build
        - stage: test
          script: yarn test
        # - stage: coverage
        #   script: yarn test:coverage
